version: '2'

services:
  codeceptjs:
    build: .
    volumes:
      - ./output:/output
      - ./tests:/tests
      - ./codecept.conf.js:/codecept.conf.js
      - ./steps_file.js:/steps_file.js
      - ./steps.d.ts:/steps.d.ts
      